#include <vector>
#include <algorithm>
#include <climits>

class Solution {
public:
    int nthSuperUglyNumber(int n, std::vector<int>& primes) {
        int k = primes.size();
        std::vector<long long> ugly(n);
        std::vector<int> idx(k, 0);
        
        ugly[0] = 1;
        
        for (int i = 1; i < n; ++i) {
            long long min_val = LLONG_MAX;
            
            // Find the minimum candidate for the next ugly number
            for (int j = 0; j < k; ++j) {
                long long candidate = (long long)ugly[idx[j]] * primes[j];
                if (candidate < min_val) {
                    min_val = candidate;
                }
            }
            
            ugly[i] = min_val;
            
            // Advance all pointers that generated the selected minimum value
            // (handles duplicate values generated by different primes)
            for (int j = 0; j < k; ++j) {
                if ((long long)ugly[idx[j]] * primes[j] == min_val) {
                    idx[j]++;
                }
            }
        }
        
        return (int)ugly[n - 1];
    }
};